In [1]:
value = 5

In [2]:
print(value)

5


In [6]:
value = 6
print(value)

6


In [2]:
thislist = ["Apple", "Oranges"]
print(thislist)

['Apple', 'Oranges']


In [3]:
thislist = ["apple", "banana", 'cherry']
print(thislist)

['apple', 'banana', 'cherry']


In [4]:
thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)


['apple', 'banana', 'cherry', 'apple', 'cherry']


In [5]:
print(len(thislist))

5


In [10]:
list1 = ["abc", 34, True, 40, "male", "a", "a"]


In [11]:
print(list1)
list1[0] = "xyz"
print(list1)

['abc', 34, True, 40, 'male', 'a', 'a']
['xyz', 34, True, 40, 'male', 'a', 'a']


In [12]:
print(type(list1))

<class 'list'>


In [13]:
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)


['apple', 'banana', 'cherry']


In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy 

In [12]:
thistuple = ("Ali", 2, "A", "A")

In [13]:
print(thistuple)

('Ali', 2, 'A', 'A')


In [4]:
print(thistuple[2])


A


In [9]:
thistuple[2] = "ABC"


TypeError: 'tuple' object does not support item assignment

In [14]:
thistuple = ("apple", "banana", "cherry", "apple", "cherry") 
print(thistuple)

('apple', 'banana', 'cherry', 'apple', 'cherry')


In [25]:
thistuple = ("Apple")

In [26]:
print(thistuple)

Apple


In [27]:
print(type(thistuple))

<class 'str'>


In [28]:
tuple1 = ("abc", 34, True, 40, "male")
print(tuple1)

('abc', 34, True, 40, 'male')


In [29]:
print(type(tuple1))

<class 'tuple'>


In [38]:
thisset = {"apple", "banana", "cherry", "apple"}
print(thisset)

{'apple', 'cherry', 'banana'}


In [34]:
print(thisset)

{'apple', 'cherry', 'banana'}


In [35]:
thisset[0]

TypeError: 'set' object is not subscriptable

In [36]:
print(thisset[0])

TypeError: 'set' object is not subscriptable

In [37]:
print(thisset)



{'apple', 'cherry', 'banana'}


In [39]:
print(len(thisset))

3


In [40]:
set1 = {"abc", 34, True, 40, "male"}
print(set1)

{True, 34, 40, 'abc', 'male'}


In [41]:
print(type(set1))

<class 'set'>


In [44]:
thisset = set({"apple", "banana", "cherry"}) # note the double round-brackets 
print(thisset)

{'apple', 'cherry', 'banana'}


In [51]:
thisdict = {"brand": "Ford", "model": "Mustang", "year": 1964}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [53]:
thisdict['brand'] = "Toyota"

In [54]:
print(thisdict)

{'brand': 'Toyota', 'model': 'Mustang', 'year': 1964}


In [56]:
thisdict = {
"brand": "Ford", "model": "Mustang", "year": 1964,"year": 2020, "brand" :"Alto"} 
print(thisdict)

{'brand': 'Alto', 'model': 'Mustang', 'year': 2020}


In [57]:
print(len(thisdict))

3


In [58]:
print(type(thisdict))

<class 'dict'>


In [59]:
thisdict = {
"brand": "Ford",
"electric": False,
"year": 1964,
"colors": ["red", "white", "blue"]
}

In [60]:
print(thisdict)

{'brand': 'Ford', 'electric': False, 'year': 1964, 'colors': ['red', 'white', 'blue']}


In [61]:
print(len(thisdict))

4


In [1]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5])
print(arr) 


[1 2 3 4 5]


In [3]:
import numpy as np 
arr = np.array((1, 2, 3, 4, 5))
print(arr) 

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>
