In [31]:
            #toes %win #fans
weights = [ [0.1, 0.1, -0.3], #hurt?
            [0.1, 0.2, 0.0], #win?
            [0.0, 1.3, 0.1] ] #sad?

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]


    
def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred
    

pred = neural_network(input, weights)
print(pred)


    

[0.555, 0.9800000000000001, 0.9650000000000001]


In [48]:
import numpy as np
#toes %win #fans

    
ih_wgt = np.array([ [0.1, 0.2, -0.1], #hid[0]
           [-0.1,0.1, 0.9], #hid[1]
           [0.1, 0.4, 0.1] ]) #hid[2]

           #hid[0] hid[1] hid[2]
hp_wgt = np.array ([ [0.3, 1.1, -0.3], #hurt?
           [0.1, 0.2, 0.0], #win?
           [0.0, 1.3, 0.1] ]) #sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

# Input corresponds to every entry
# for the first game of the season.

input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)

print(pred)

[ 0.496  1.256 -0.286]


In [38]:
import numpy as np

a = np.array([0,1,2,3]) # a vector


b = np.array([4,5,6,7]) # another vector

c = np.array([[0,1,2,3], # a matrix
              [4,5,6,7]])

d = np.zeros((2,4)) # (2x4 matrix of zeros)

e = np.random.rand(2,5)# random 2x5
# matrix with all numbers between 0 and 1

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.31765313 0.18969353 0.82419222 0.24298545 0.01818749]
 [0.66837052 0.82700783 0.72330507 0.89959129 0.62179491]]


In [46]:
# print(a * 0.1) # multiplies every number in vector "a" by 0.1
      
#print(c * 0.2) # multiplies every number in matrix "c" by 0.2
      

#print(a * b) # multiplies elementwise between a and b (columns paired up)
      
#print(a * b * 0.2) # elementwise multiplication then multiplied by 0.2
      
#print(a * c) # since c has the same number of columns as a, this performs
# elementwise multiplication on every row of the matrix "c"

 #print(a * e) # since a and e don't have the same number of columns, this
# throws a "Value Error: operands could not be broadcast together with.."




IndentationError: unexpected indent (<ipython-input-46-9d426c9bb9df>, line 13)

In [ ]:
a = np.zeros((1,4)) # vector of length 4
b = np.zeros((4,3)) # matrix with 4 rows & 3 columns

c = a.dot(b)
print(c.shape)